[package]
name = "r_wsproto"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"
prost = "0.9.0"
tungstenite = "0.16.0"
url = "2.2.2"

[build-dependencies]
prost-build = "0.9.0"